### ISSUE TITLE
Allow customisation of CP nav title?

### ISSUE THREAD

**Issue by johndwells** [boboldehampsink/translate#10]
Could you add in a settings where we can change the name of the CP tab from "Translate" to anything we want?

The specific use case I have in mind is when I want to use Translate to simply give the client a way to edit any phrase across the site.  It's not a multi-lingual site, but by using t() filters we can give clients the ability, down the road, to tweak calls to actions, headers, and other elements that don't suit making a global variable etc for.

In this instance, "Translate" isn't really the right label; but something like "Site Phrases" is perfect.

:)

**Comment by boboldehampsink** [comment]
You could easily do this by installing a plugin like https://github.com/engram-design/CPNav/

**Comment by johndwells** [comment]
Good point! :)
