### ISSUE TITLE
Plugin still maintained?

### ISSUE THREAD

**Issue by FrancisBou** [boboldehampsink/translate#17]
There are a few issues with this plugin, is it still maintained?
The plugin won't display de strings that have already been translated, it always override previous changes and all plugin strings are in the same file. 
On a clean install with only this plugin and the one I want to translate.

**Comment by DiederikVanHoorebeke** [comment]
I have the same issue.

I've set the `defaultCpLanguage` in the config file.

Also, I found the translation in the plugin folder, and it contained the translations. But in the CP, the status of the translation hasn't changed and the translations aren't being loaded.

Specs:
- craft personal 2.6.2791
- test environment using php7

**Comment by FrancisBou** [comment]
The problem seems to be that the plugin does not load those translations even if they are in the generated file, it returns the original string:

**Comment by boboldehampsink** [comment]
I haven't tested this plugin with Craft 2.6 or with PHP7. This plugin accepts Pull Requests but is not actively maintained.

**Comment by outline4** [comment]
I have the same problem. The plugin is a great idea, but it would need some serious love...
