### ISSUE TITLE
Problems saving translations

### ISSUE THREAD

**Issue by fernandoigual** [boboldehampsink/translate#6]
Hello.

We've experimented a problem saving translations. Randomly, I don't know how, we save one o multiple translations and they haven't been saved. When we return to search for them, last translated text is instead of saved.

I don't know how isolate this problem to help you to resolve it.

Thank you in advance.

**Comment by boboldehampsink** [comment]
Are you perhaps using something like OPcache, APC (etc.)?

**Comment by fernandoigual** [comment]
No, I don't :(

**Comment by boboldehampsink** [comment]
Does this happen on all your installations, or just one?

**Comment by fernandoigual** [comment]
Hi again.

This happends on all translations.
We have noticed that translations saved aren't (sometimes) showed if we search for them immediately. The result of this search is old translated text. I think is a cache problem.

**Comment by boboldehampsink** [comment]
You think this is a browser cache problem? Or server cache?

**Comment by fernandoigual** [comment]
Howether this problem happens sometimes, I will log browser requests for responding your question.

**Comment by fernandoigual** [comment]
Our customer has detected when they save a translation with empty string,  search for it (then translation has the orange indicator), write new translation text and save it again, then the translation was saved correctly.

**Comment by boboldehampsink** [comment]
Thanks, I have isolated the problem and will fix it

**Comment by boboldehampsink** [comment]
Could you try the latest develop branch? I think I fixed it

**Comment by fernandoigual** [comment]
I'm going to try now

**Comment by fernandoigual** [comment]
Hello again.
I've seen your last commit code and the only change was an "if" before change download button link. I've tried and works but, I don't know if it will fail again.
I will tell you...

**Comment by boboldehampsink** [comment]
This bug sometimes set an "empty" locale, so when you were saving it wouldn't really save - describing the issue you had

**Comment by fernandoigual** [comment]
Ah Ok! I've see now!
A lot of thanks!
